USE SP_MEDICAL_GROUP
GO

SELECT * FROM CLINICA
SELECT * FROM CONSULTA
SELECT * FROM ESPECIALIDADE
SELECT * FROM MEDICO
SELECT * FROM PACIENTE	
SELECT * FROM SITUACAO
SELECT * FROM TIPOUSUARIO
SELECT * FROM USUARIO

SELECT * FROM MEDICO
WHERE CONSULTA.idMedico = 1

SELECT * FROM MEDICO
WHERE CONSULTA.idPaciente = 3

SELECT COUNT(email) FROM USUARIO

SELECT *, CONVERT(VARCHAR, CONVERT(DATE, dataNascPac, 103), 110) FROM Paciente

EXEC MedicoPorEspecialidade @idEspecialidade = 1

EXEC CalcularIdade 1